
version: "3.9"

services:

  mongodb:
    image: docker.io/mongo:7-jammy
    ports:
      - "3010:27017"

  backend:
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      bindAddress: 0.0.0.0
      mongodbUrl: mongodb://mongodb/real_world
    build:
      dockerfile: backend/Dockerfile
    ports:
      - "3090:2010"

volumes:
  mongodb:
  mongodb-data:
    driver: local
