
version: "3.9"

services:

  mongodb:
    image: docker.io/mongo:7-jammy
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "3010:27017"

  backend:
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      bindAddress: 0.0.0.0
      mongodbUrl: mongodb://mongodb/real_world
    image: ${REGISTRY:-}backend
    build:
      dockerfile: backend/distribution.dockerfile
    ports:
      - "3090:2010"

volumes:
  mongodb:
