
services:

  mongodb:
    image: docker.io/mongo:6.0-jammy
    ports:
      - "3010:27017"

  backend:
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      bindAddress: 0.0.0.0
      mongodbUrl: mongodb://mongodb/real_world
    build:
      context: backend
    ports:
      - "3090:2010"
