
name: real_world

services:

  mongodb:
    image: docker.io/mongo:7-jammy
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: real_world
    ports:
      - "3010:27017"

  backend:
    labels:
      app: realworld
      type: backend
    depends_on:
      - mongodb
    environment:
      bindAddress: 0.0.0.0
      # TODO This should be a secret
      mongodbUrl: mongodb://root:password@mongodb/real_world?authSource=admin
    image: ${REGISTRY:-}backend
    build:
      dockerfile: backend/distribution.dockerfile
    ports:
      - "3090:2010"

volumes:
  mongodb:
    driver: local
