
apiVersion: v1
kind: Service

metadata:
  annotations:
    app: realworld
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s
    kompose.version: 1.31.0 (HEAD)
    type: backend
  labels:
    io.kompose.service: backend
  name: backend

spec:
  ports:
    - name: "3090"
      port: 3090
      targetPort: 2010
  selector:
    io.kompose.service: backend
