
name: GitHub CI
on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - uses: graalvm/setup-graalvm@v1
        with:
          version: latest
          distribution: graalvm-community
          java-version: 21
          cache: gradle
      - run: .github/pre-push.sh
